hyperskill_project:
  id: 175
  ide_files: https://stepik.org/media/attachments/lesson/517618/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 901
  step: 12898
  is_completed: false
- id: 902
  step: 12899
  is_completed: false
- id: 903
  step: 12900
  is_completed: false
- id: 904
  step: 12901
  is_completed: false
